# Generated by Django 5.2.17 on 2026-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='references',
            field=models.TextField(blank=True, help_text='Una referencia por linea, con el formato "Texto de la referencia | URL". En el contenido se citan como [1], [2]... segun el orden de esta lista.'),
        ),
    ]
