# Generated by Django 5.2.17 on 2026-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text="A partir de cuantas unidades una variante se marca como 'stock bajo'.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del panel',
                'verbose_name_plural': 'Configuracion del panel',
            },
        ),
    ]
