# Generated by Django 5.2.17 on 2026-10-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelsettings',
            name='monthly_sales_goal',
            field=models.PositiveIntegerField(default=0, help_text='Meta de ingresos (COP) para el rango de fechas consultado en el panel. 0 desactiva la barra de progreso.'),
        ),
    ]
