# Generated by Django 5.2.17 on 2026-09-30 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sincroniza_roles_de_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Ej. Casa, Oficina', max_length=60)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=40)),
                ('country', models.CharField(default='Colombia', max_length=80)),
                ('department', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('address_complement', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='customer_segments',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.customersegment', verbose_name='Segmentos de cliente'),
        ),
    ]
