# Generated by Django 5.2.17 on 2026-09-30 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_inventory_from_product_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positivo si suma stock, negativo si lo descuenta.')),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('manual', 'Ajuste manual'), ('sale', 'Venta'), ('restock', 'Reposicion (cancelacion o devolucion)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Vacio si el ajuste lo disparo el sistema (venta o reposicion), no una persona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
