# Generated by Django 4.2.21 on 2025-05-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/placeholder.webp', upload_to='products/images'),
        ),
    ]
