# Generated by Django 4.2.21 on 2025-06-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/images/placeholder.png', upload_to='products/images'),
        ),
    ]
