# Generated by Django 5.2.17 on 2026-10-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_backfill_media_from_legacy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio vigente con descuento, en valor a pagar. Si es menor que el precio normal, es el que se cobra y el normal se muestra tachado.', max_digits=12, null=True),
        ),
    ]
