# Generated by Django 5.2.17 on 2026-09-18 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=80)),
                ('method_name', models.CharField(max_length=80)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_days', models.PositiveIntegerField()),
                ('tracking_code', models.CharField(blank=True, max_length=64)),
                ('shipping_status', models.CharField(default='pending', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_quote', to='orders.order')),
            ],
        ),
    ]
