# Generated by Django 5.2 on 2025-05-19 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(blank=True, null=True, verbose_name='NIT')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('logo', models.ImageField(default='logos/usergenerics.png', upload_to='logos/', verbose_name='Cargar Logo')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre de la Persona a Cargo')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id'],
            },
        ),
    ]
