# Generated by Django 5.2.17 on 2026-09-29 22:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
        ('orders', '0006_coupon_influencer_order_referred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Porcentaje que gana el afiliado sobre el neto del pedido, si el afiliado no tiene una tasa propia.', max_digits=5)),
                ('default_customer_discount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Porcentaje de descuento que recibe el cliente final al usar el codigo de un afiliado nuevo.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del programa de afiliados',
                'verbose_name_plural': 'Configuracion del programa de afiliados',
            },
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de revision'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='approved', max_length=12),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('rejected', 'Rechazada')], default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='influencer.influencerprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('paid', 'Pagada'), ('reverted', 'Revertida')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='influencer.influencerprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.order')),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='influencer.withdrawalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
