# Generated by Django 5.2.17 on 2026-09-30 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_influencerprogramsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_clicks', to='influencer.influencerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
