# Generated by Django 5.2.17 on 2026-09-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_influencerprofile_terms_accepted_at_referralclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa propia de este afiliado. Vacio usa la tasa global del programa.', max_digits=5, null=True),
        ),
    ]
