# Generated by Django 5.2.17 on 2026-10-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_influencerprofile_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_details',
            field=models.TextField(blank=True),
        ),
    ]
