# Generated by Django 5.2.17 on 2026-09-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_seed_legacy_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('confirmed', 'Confirmado'), ('preparing', 'En preparacion'), ('shipped', 'Enviado'), ('in_transit', 'En transito'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('returned', 'Devolucion')], default='pending_payment', max_length=20),
        ),
    ]
