# Generated by Django 5.2.17 on 2026-09-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customersegment_customeraddress_and_more'),
        ('orders', '0006_coupon_influencer_order_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='customer_segment',
            field=models.ForeignKey(blank=True, help_text='Si se asigna, solo los clientes de este segmento pueden usar el cupon (precio diferenciado por segmento).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='accounts.customersegment'),
        ),
    ]
