# Generated by Django 5.2.17 on 2026-09-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAnalitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=64)),
                ('ruta', models.CharField(blank=True, max_length=300)),
                ('sesion', models.CharField(blank=True, db_index=True, max_length=64)),
                ('autenticado', models.BooleanField(default=False)),
                ('propiedades', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'evento de analitica',
                'verbose_name_plural': 'eventos de analitica',
                'ordering': ('-creado',),
                'indexes': [models.Index(fields=['nombre', 'creado'], name='analitica_e_nombre_555301_idx')],
            },
        ),
    ]
